name: shifter-dev
channels:
  - conda-forge
  - defaults 
  - nlesc
  - sbu-hpc 
dependencies:
  - python==3.6
  - six 
  - setuptools 
  - pytest 
  - cmake 
  - rapidjson 
  - gcc 
  - curl 
  - cmake 
  - json-c 
  - libtool 
  - autoconf 
  - automake 
  - wget 
  - gflags 
  - cython 
  - glibc 
  - mongodb 
  - squashfs-tools 

