#!/usr/bin/env bash
#HPCI -n conda
#HPCI -v 4
#HPCI -u https://conda.io/docs/index.html/

echo "Downloading and installing Miniconda..."

# terminate this script immediately should anything go wrong
set -e

mkdir -p $HPCI_SW_DIR


# Download Miniconda and run install in batch mode (without manual intervention),
# it is expected the license terms are agreed upon and specify install prefix
 
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
bash miniconda.sh -b -p $HPCI_SW_DIR/miniconda

# Check for Conda installation Info
export PATH="$HPCI_SW_DIR/miniconda/bin:$PATH"
hash -r 
conda config --set always_yes yes --set changeps1 no
echo "Printing Conda Current Installation info....."
conda info -a

echo "End of Conda Current Installation info...."

# Create the module directory, if needed
mkdir -p $HPCI_MOD_DIR/$HPCI_SW_NAME/

# Create the module with the following template
cat << EOF > $HPCI_MOD_DIR/$HPCI_SW_NAME/${HPCI_SW_VERSION}.lua
require("posix")

whatis("$HPCI_SW_NAME v$HPCI_SW_VERSION")

help([[
This module loads conda package manager.
See https://conda.io/docs/index.html/ for details.
]])

local verpath = "$HPCI_SW_DIR/miniconda"                    -- specific version path
local binpath = pathJoin(verpath, "bin")                    -- internal python libs
-- similarly for includes or others

prepend_path("PATH", binpath)
conflict("python")
prereq($HPCI_MOD_PREREQ)
EOF
