#!/usr/bin/env bash
#HPCI -n conda
#HPCI -v 4
#HPCI -u https://conda.io/docs/
echo "........conda module creation started........"
echo "Downloading and installing Miniconda..."

# terminate this script immediately should anything go wrong
set -e

export HPCI_SW_DIR=/glade/work/abanihi/softwares

# Download Miniconda and run install in batch mode (without manual intervention),
# it is expected the license terms are agreed upon and specify install prefix
export INSTALL_PATH=$HPCI_SW_DIR/miniconda3
echo "Installation Path is created at"
echo $INSTALL_PATH

wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
bash miniconda.sh -b -p $INSTALL_PATH

echo "Finished installing miniconda"
# Check for Conda installation Info
export PATH="$INSTALL_PATH/bin:$PATH"
echo $PATH 
hash -r 
conda config --set always_yes yes --set changeps1 no
echo "Printing Conda Current Installation info....."
conda info -a

echo "End of Conda Current Installation info...."

# Create the module directory, if needed
mkdir -p $HPCI_MOD_DIR/$HPCI_SW_NAME/

# Create the module with the following template
cat << EOF > $HPCI_MOD_DIR/$HPCI_SW_NAME/${HPCI_SW_VERSION}.lua
require("posix")

whatis("$HPCI_SW_NAME v$HPCI_SW_VERSION")

help([[
This module loads conda package manager.
See https://conda.io/docs/ for more details.

To create and install your own conda module, 
check https://github.com/andersy005/modules-cheyenne out. 

]])

local verpath = "$INSTALL_PATH"                    -- specific version path
local binpath = pathJoin(verpath, "bin")                    -- internal python libs
-- similarly for includes or others

prepend_path("PATH", binpath)
conflict("python")
prereq($HPCI_MOD_PREREQ)
EOF

echo "Making conda's root environment permission to read only"
chmod 444 $INSTALL_PATH/conda-meta/history
echo "........conda module creation completed successfully........\n\n\n"
cat $HPCI_SW_DIR/$HPCI_SW_NAME/${HPCI_SW_VERSION}/BUILD_DIR/hpci.main.log

printf "\n\tTo load the conda module, you will need to run\n 
    \tmodule use <HPCI_MOD_DIR>\n
    \tmodule load conda\n
      \tNOTE: Replace HPCI_MOD_DIR with the corresponding value printed above.\n"